### PR TITLE
S24/jonathan/adding user roles

### PR DESCRIPTION
**Pull request by jonathankim345**
## Notion ticket link

[User Fields](https://www.notion.so/uwblueprintexecs/User-Fields-c2e4b32a85fb4cf98c6d73ef5343eb0a?pvs=4)

## Steps to test
1. Verify generated migration files
2. Verify proper fields in place
Example: 
Screenshot 2024-06-22 125421

## Checklist
- [ ✔️] My PR name is descriptive and in imperative tense
- [ ✔️] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [✔️ ] I have run the appropriate linter(s)
- [✔️ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by aanxniee — APPROVED** [review]
lgtm, let's wait for jerry's approval

**Review by jerry-cheng5 — APPROVED** [review]
Looks good!

Something I just noticed on this PR that I overlooked on previous ones is the consistency between the columns in the table and the columns in the sequelize models.

To keep things consistent, all not nullable columns should also be non-nullable in the model, and same for nullable columns.

I did some quick research, and it isn't absolutely necessary, since sequelize will try to automatically infer the column properties (data type, nullable, etc). But for the sake of consistency and code readability, it might be a good investment to do this.

Here's how I recommend we update it:
- For non-nullable columns, we update the decorator to something like `@Column({ type: DataType.INTEGER, allowNull: false})`
- For nullable columns, we don't need to change the decorator since `allowNull` defaults to true, but we should change the typescript variable to be something like `skill_level?: number | null`, so that it is an optional value when we want to create a User, and it can be nullable to match the database column

Because this isn't absolutely necessary, I say just merge this PR and we can do a fix for all the tables at the end, since some are already merged without this detail.

**Comment by jonathankim345** [comment]
@aanxniee great thank you!

**Comment by jonathankim345** [comment]
@jerry-cheng5 I really appreciate the feedback! That's a great point about the nullable values for the table columns. By the data types do you mean whether an integer or string can be nullable? That's a great suggestion, I'll merge this PR and it can be a focus for our next sprint.

**Pull request merged**
